# SPDX-License-Identifier: MIT
# emulator_top — build everything for the image described by platform/config.
#
#     make            # hwdef + probes, libpim + libpimrt, their test binaries, pim.ko
#     make info       # what platform/config selects
#     make clean
#
# platform/config says which image is on the board (CH, REV) and which channel
# address map to use (ADDR_MAP).  hwdef/gen_config.sh reads it.
#
# Board steps are separate:
#     hwdef/test/emu_sanity          check the board; also sets its map register to ADDR_MAP
#     make -C sw/drv load            insmod pim.ko (defaults are platform/config's values)
#     make -C sw test                run the tests

.PHONY: all hwdef lib runtime lib-test runtime-test drv info clean

all: hwdef lib runtime lib-test runtime-test drv

# libhwdef.a and the probes.  Generates hwdef/pim_config.h from platform/config.
hwdef:
	$(MAKE) -C hwdef test

# Topology comes from the driver at run time.
lib:
	$(MAKE) -C sw/lib

runtime: lib
	$(MAKE) -C sw/runtime

# Test binaries, built but not run.  lib/test compiles hwdef sources itself.
lib-test: hwdef
	$(MAKE) -C sw/lib/test all

runtime-test: runtime
	$(MAKE) -C sw/runtime/test all

drv:
	$(MAKE) -C sw/drv

info:
	@$(MAKE) -s -C hwdef pim_config.h
	@sed -n 's|^// GENERATED by hwdef/gen_config.sh from ||p; s|^// and \(platform/[^ ]*\)\..*|         \1|p' hwdef/pim_config.h
	@grep -E '^#define PIM_(NCH|NBANK|BANK_STRIDE|BANK_WINDOW|MC_BASE|ADDR_MAP) ' hwdef/pim_config.h

clean:
	$(MAKE) -C hwdef clean
	$(MAKE) -C sw/lib clean
	$(MAKE) -C sw/runtime clean
	-$(MAKE) -C sw/drv clean
