#!/usr/bin/env bash
# gen_config.sh — turn platform/config into what the build and the driver use.
#
#     ./gen_config.sh --header FILE   # write pim_config.h.  hwdef/Makefile runs this.
#
# Inputs: platform/config (CH, REV, ADDR_MAP) and the image conf CH/REV select,
# platform/ch<CH>[_<REV>].conf.  Both are cleared of inherited values before they
# are read, so only what the files say is used, and a missing key is an error.
#
# --header rewrites the file only when its content changes, so make rebuilds only
# what depends on a changed value.
#
# Addresses carry ULL and counts u, to match their use as 64-bit / unsigned.
set -euo pipefail

MODE=""
OUT=""
case "${1:-}" in
    --header) MODE=header; OUT="${2:-}"
              [[ -n "$OUT" ]] || { echo "gen_config.sh: --header needs an output path" >&2; exit 2; } ;;
    -h|--help)
        awk 'NR>1 && /^#/ {sub(/^# ?/, ""); print; next} NR>1 {exit}' "${BASH_SOURCE[0]}"
        exit 0 ;;
    *) echo "gen_config.sh: expected --header FILE" >&2; exit 2 ;;
esac

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLATFORM_DIR="$(cd "$HERE/../platform" && pwd)"
SEL="$PLATFORM_DIR/config"

die() { echo "gen_config.sh: $*" >&2; exit 2; }

if [[ ! -r "$SEL" ]]; then
    die "no $SEL — set up which image is on the board:
               cp $PLATFORM_DIR/config.example $SEL   and edit CH / ADDR_MAP"
fi

# ---- the user's choice ----
unset CH REV ADDR_MAP
# shellcheck disable=SC1090
source "$SEL"
[[ "${CH:-}" =~ ^[0-9]+$ ]] || die "$SEL: CH must be a channel count, got '${CH:-}'"
REV="${REV:-}"
# ADDR_MAP is 1 or 2; PIM_ADDR_MAP is the MODE_CTRL bit, 0 or 1.
case "${ADDR_MAP:-}" in
    1) MAPBIT=0 ;;
    2) MAPBIT=1 ;;
    *) die "$SEL: ADDR_MAP must be 1 (ChRoBaCo) or 2 (RoChBaCo), got '${ADDR_MAP:-}'" ;;
esac

# ---- which image conf ----
# REV given: ch<CH>_<REV>.conf.  REV empty: the single ch<CH>.conf or ch<CH>_*.conf;
# if there are several, REV must name one.
shopt -s nullglob
if [[ -n "$REV" ]]; then
    CANDS=("$PLATFORM_DIR/ch${CH}_${REV}.conf")
    [[ -r "${CANDS[0]}" ]] || CANDS=()
else
    CANDS=("$PLATFORM_DIR/ch${CH}.conf" "$PLATFORM_DIR/ch${CH}"_*.conf)
    _e=(); for c in "${CANDS[@]}"; do [[ -r "$c" ]] && _e+=("$c"); done; CANDS=("${_e[@]}")
fi
shopt -u nullglob
_avail="$(cd "$PLATFORM_DIR" && ls ch*.conf 2>/dev/null | sed 's/\.conf$//' | tr '\n' ' ')"
if (( ${#CANDS[@]} == 0 )); then
    die "$SEL: no conf for CH=$CH${REV:+ REV=$REV}.  available: $_avail"
elif (( ${#CANDS[@]} > 1 )); then
    _revs=(); for c in "${CANDS[@]}"; do c="${c##*/}"; c="${c%.conf}"; _revs+=("${c#ch${CH}_}"); done
    die "$SEL: CH=$CH matches several confs — set REV to one of: ${_revs[*]}"
fi
CONF="${CANDS[0]}"
NAME="$(basename "$CONF" .conf)"

KEYS=(NCH NBANK BAR2_AXI_BASE OFF_GPR OFF_CFR OFF_VIOL OFF_IMEM
      HBM_BASE HBM_CH_SPAN HBM_BANK_STRIDE BANK_WINDOW
      MC_BASE MC_SPAN UPLOAD_PATH NTAIL_POLICY SCHEDULE FEATURE_T_LATCH)

unset "${KEYS[@]}"

# shellcheck disable=SC1090
source "$CONF"

req() { [[ -n "${!1:-}" ]] || { echo "gen_config.sh: $CONF has no $1" >&2; exit 2; }; }
for k in "${KEYS[@]}"; do
    req "$k"
done

# The conf's own NCH must match the CH that selected it.
[[ "$NCH" == "$CH" ]] || die "$CONF says NCH=$NCH but was selected by CH=$CH"

# The path lands inside a C string literal.
case "$SEL$REV" in
    *'"'*|*'\'*) die "a quote or backslash cannot go in a C string: $SEL / REV=$REV" ;;
esac

TMP="$(mktemp "${OUT}.XXXXXX")"
trap 'rm -f "$TMP"' EXIT
cat > "$TMP" <<HDR
// GENERATED by hwdef/gen_config.sh from platform/config (CH=$CH REV=$REV ADDR_MAP=$ADDR_MAP)
// and platform/${NAME}.conf.  Do not edit: edit platform/config and run make.
#ifndef PIM_CONFIG_H
#define PIM_CONFIG_H

#define PIM_PLATFORM_NAME   "$NAME"

// What platform/config said at build time.  pim_platform_check() reads the file
// again at run time and refuses a binary that no longer matches it.
#define PIM_CONFIG_PATH     "$SEL"
#define PIM_SEL_CH          ${CH}u
#define PIM_SEL_REV         "$REV"
#define PIM_SEL_ADDR_MAP    ${ADDR_MAP}u

// ---- topology ----
#define PIM_NCH             ${NCH}u
#define PIM_NBANK           ${NBANK}u

// ---- control plane (BAR2) ----
#define PIM_BAR2_AXI_BASE   ${BAR2_AXI_BASE}ULL
#define PIM_OFF_GPR         ${OFF_GPR}ULL
#define PIM_OFF_CFR         ${OFF_CFR}ULL
#define PIM_OFF_VIOL        ${OFF_VIOL}ULL
#define PIM_OFF_IMEM        ${OFF_IMEM}ULL

// ---- path A: direct HBM.  WINDOW IS NOT STRIDE ----
#define PIM_HBM_BASE        ${HBM_BASE}ULL
#define PIM_HBM_CH_SPAN     ${HBM_CH_SPAN}ULL
#define PIM_BANK_STRIDE     ${HBM_BANK_STRIDE}ULL
#define PIM_BANK_WINDOW     ${BANK_WINDOW}ULL

// ---- path B: MC s_axi ----
#define PIM_MC_BASE         ${MC_BASE}ULL
#define PIM_MC_CH_SPAN      ${MC_SPAN}ULL

// ---- policy ----
#define PIM_UPLOAD_PATH     "${UPLOAD_PATH}"
#define PIM_NTAIL_POLICY    "${NTAIL_POLICY}"
#define PIM_SCHEDULE        "${SCHEDULE}"
#define PIM_FEATURE_T_LATCH ${FEATURE_T_LATCH}

// The channel address map as MODE_CTRL's bit: 0 ChRoBaCo, 1 RoChBaCo (ADDR_MAP=${ADDR_MAP}).
#define PIM_ADDR_MAP        ${MAPBIT}

#endif // PIM_CONFIG_H
HDR

# Leave the file (and its timestamp) alone when nothing changed.
if cmp -s "$TMP" "$OUT"; then
    exit 0
fi
mv "$TMP" "$OUT"
trap - EXIT
echo "gen_config.sh: $OUT <- $NAME" >&2
